stages:
    - deploy
  
deploy_production:
    stage: deploy
    tags:
        - shell, xvrqt-static-01
    script:
        - cp -p nginx.conf /etc/nginx/sites-enabled/homepage
        - mkdir -p /var/www/homepage
        - cp -pr src/* /var/www/homepage/
        - sudo nginx -t && sudo service nginx reload
    environment:
        name: production
        url: https://xvrqt.com
    when: manual
