stages:
    - build
    - deploy

image: node:11.4

cache:
  paths:
    - node_modules/
    - dist/

build:
  stage: build
  script:
    - echo "Testing if the app builds"
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
      
deploy_staging:
  stage: deploy
  script:
    - echo "Deploying to staging server"
    - cp -r dist/* /var/www/homepage/
  environment:
    name: staging
    url: https://stg.xvrqt.com
  only:
  - master
  
deploy_production:
  stage: deploy
  script:
    - echo "Deploying to production server"
    - scp -r dist/* root@static-01:/var/www/homepage
  environment:
    name: production
    url: https://xvrqt.com
  when: manual
  only:
  - tags

