stages:
    - deploy
  
deploy_production:
    stage: deploy
    tags:
        - shell, xvrqt-static-01
    script:
        - cp -p nginx.conf /etc/nginx/sites-enabled/homepage
        - cp -pr src/* /var/www/homepage/
        - nginx -t && service nginx reload
    environment:
        name: production
        url: https://xvrqt.com
    when: manual
      only:
          - master
          - tags

