stages:
    - deploy
    - certify

deploy:
    stage: deploy
    tags:
        - shell, xvrqt-static-01
    script:
        - cp nginx.conf /etc/nginx/sites-enabled/homepage
        - mkdir -p /var/www/homepage
        - cp -r src/* /var/www/homepage/
        - sudo nginx -t && sudo service nginx reload
    environment:
        name: production
        url: https://xvrqt.com
    when: manual

certify:
    stage: certify
    tags:
        - shell, xvrqt-static-01
    script:
        - certbot --nginx -d xvrqt.com < /etc/nginx/certbot_prompt.txt
        - certbot --nginx -d crates.xvrqt.com < /etc/nginx/certbot_prompt.txt
        - certbot --nginx -d discord.xvrqt.com < /etc/nginx/certbot_prompt.txt
        - certbot --nginx -d github.xvrqt.com < /etc/nginx/certbot_prompt.txt
        - certbot --nginx -d gitlab.xvrqt.com < /etc/nginx/certbot_prompt.txt
        - certbot --nginx -d npm.xvrqt.com < /etc/nginx/certbot_prompt.txt
        - certbot --nginx -d twitch.xvrqt.com < /etc/nginx/certbot_prompt.txt
        - certbot --nginx -d twitter.xvrqt.com < /etc/nginx/certbot_prompt.txt
    environment:
        name: production
        url: https://xvrqt.com
    when: on_success
