stages:
    - deploy
  
deploy_production:
    stage: deploy
    tags:
        - shell, xvrqt-static-01
    script:
        - cp nginx.conf /etc/nginx/sites-enabled/homepage
        - mkdir -p /var/www/homepage
        - cp src/* /var/www/homepage/
        - nginx -t && service nginx reload
    environment:
        name: production
        url: https://xvrqt.com
    when: manual
