name: Deploy Homepage to Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: 'Brotli compress html, css and js assets'
        uses: Charlesworth/compress-action@1.0.0

      - name: 'Copy NGINX config to Prod'
        uses: alinz/ssh-scp-action@v0.1.1
        with:
          host: 66.170.190.145
          user: ubuntu
          key: ${{ secrets.STATIC_02_PRIV_KEY }}
          scp: nginx.prod.conf root@68.183.251.49:/etc/nginx/sites-enabled/homepage
      
      - name: 'Copy Site to Prod'
        uses: alinz/ssh-scp-action@v0.1.1
        with:
          host: 66.170.190.145
          user: ubuntu
          key: ${{ secrets.STATIC_02_PRIV_KEY }}
          ssh_before: |
            mkdir -p /var/www/homepage
          scp: ./* ubuntu@66.170.190.145:/var/www/homepage/

